### ISSUE TITLE
菜单栏重要程度排序问题

### ISSUE THREAD

**Issue by xiangxiaobo** [zhuyuwaiting/recipe_server#1]
现在的问题是：
     登录进去，首页看到的是枚举管理

我觉得，正确的操作应该是：
* 按照重要程度来排列，1. 处方管理，2. 模板管理，3. 药品管理，4. 枚举管理
* 可以不使用两级目录，直接在菜单栏中显示这几项

**Comment by zhuyuwaiting** [comment]
done
